export const LOGGING_ENDPOINTS = {
  DIAGNOSTIC_LOGGING: "http://localhost:8001/api/logs",
};

export const LOG_TYPES = {
  BACKGROUND: "reclaim_browser_extension.BackgroundProcess",
  CONTENT: "reclaim_browser_extension.ContentScript",
  POPUP: "reclaim_browser_extension.Popup",
  INIT: "reclaim_browser_extension.Initialization",
  VERIFICATION: "reclaim_browser_extension.Verification",
  FETCH_DATA: "reclaim_browser_extension.FetchData",
  PROVIDER_DATA: "reclaim_browser_extension.ProviderData",
  CLAIM_CREATION: "reclaim_browser_extension.ClaimCreation",
  PROOF_GENERATION: "reclaim_browser_extension.ProofGeneration",
  PROOF_SUBMISSION: "reclaim_browser_extension.ProofSubmission",
  PROOF_VERIFICATION: "reclaim_browser_extension.ProofVerification",
  OFFSCREEN: "reclaim_browser_extension.Offscreen",
};

export const LOG_SOURCES = {
  BACKGROUND: "background",
  CONTENT: "content",
  OFFSCREEN: "offscreen",
  POPUP: "popup",
  INJECTION: "injection",
};

export const EVENT_TYPES = {
  IS_RECLAIM_EXTENSION_SDK: "IS_RECLAIM_EXTENSION_SDK",
  VERIFICATION_FLOW_STARTED: "VERIFICATION_FLOW_STARTED",
  RECLAIM_VERIFICATION_DISMISSED: "RECLAIM_VERIFICATION_DISMISSED",
  RECLAIM_VERIFICATION_PROVIDER_LOAD_EXCEPTION: "RECLAIM_VERIFICATION_PROVIDER_LOAD_EXCEPTION",
  REQUEST_MATCHED: "REQUEST_MATCHED",
  RESPONSE_MATCH_FAILED: "RESPONSE_MATCH_FAILED",
  X_PATH_MATCH_REQUIREMENT_FAILED: "X_PATH_MATCH_REQUIREMENT_FAILED",
  JSON_PATH_MATCH_REQUIREMENT_FAILED: "JSON_PATH_MATCH_REQUIREMENT_FAILED",
  REGEX_MATCH_REQUIREMENT_FAILED: "REGEX_MATCH_REQUIREMENT_FAILED",
  FILTERED_REQUEST_FOUND: "FILTERED_REQUEST_FOUND",
  FILTER_REQUEST_ERROR: "FILTER_REQUEST_ERROR",
  STARTING_CLAIM_CREATION: "STARTING_CLAIM_CREATION",
  CLAIM_CREATION_STARTED: "CLAIM_CREATION_STARTED",
  CLAIM_CREATION_SUCCESS: "CLAIM_CREATION_SUCCESS",
  CLAIM_CREATION_FAILED: "CLAIM_CREATION_FAILED",
  CLAIM_PARAMETER_VALIDATION_FAILED_EXCEPTION: "CLAIM_PARAMETER_VALIDATION_FAILED_EXCEPTION",
  OFFSCREEN_DOCUMENT_READY: "OFFSCREEN_DOCUMENT_READY",
  OFFSCREEN_DOCUMENT_NOT_READY_EXCEPTION: "OFFSCREEN_DOCUMENT_NOT_READY_EXCEPTION",
  PROOF_GENERATION_STARTED: "PROOF_GENERATION_STARTED",
  PROOF_GENERATION_SUCCESS: "PROOF_GENERATION_SUCCESS",
  PROOF_GENERATION_ABORTED: "PROOF_GENERATION_ABORTED",
  PROOF_GENERATION_FAILED: "PROOF_GENERATION_FAILED",
  RESULT_RECEIVED: "RESULT_RECEIVED",
  SUBMITTING_PROOF: "SUBMITTING_PROOF",
  SUBMITTING_PROOF_TO_CALLBACK_URL: "SUBMITTING_PROOF_TO_CALLBACK_URL",
  SUBMITTING_PROOF_TO_CALLBACK_URL_SUCCESS: "SUBMITTING_PROOF_TO_CALLBACK_URL_SUCCESS",
  SUBMITTING_PROOF_TO_CALLBACK_URL_FAILED: "SUBMITTING_PROOF_TO_CALLBACK_URL_FAILED",
  PROOF_SUBMISSION_FAILED: "PROOF_SUBMISSION_FAILED",
  PROOF_SUBMITTED: "PROOF_SUBMITTED",
  VERIFICATION_FLOW_FAILED: "VERIFICATION_FLOW_FAILED",
  TAB_NOT_MANAGED_BY_EXTENSION_EXCEPTION: "TAB_NOT_MANAGED_BY_EXTENSION_EXCEPTION",
  INJECTION_SCRIPT_SET_IN_LOCAL_STORAGE_FAILED: "INJECTION_SCRIPT_SET_IN_LOCAL_STORAGE_FAILED",
  VERIFICATION_POPUP_ERROR: "VERIFICATION_POPUP_ERROR",
  UPDATE_SESSION_STATUS_ERROR: "UPDATE_SESSION_STATUS_ERROR",
};

// Numeric levels for easy threshold checks
export const LOG_LEVEL = {
  INFO: 10,
  DEBUG: 20,
  ALL: 30,
};

export const LOG_LEVEL_MAP = {
  INFO: LOG_LEVEL.INFO,
  DEBUG: LOG_LEVEL.DEBUG,
  ALL: LOG_LEVEL.ALL,
};

export const DEFAULT_LOG_CONFIG = {
  logLevel: "INFO", // "INFO" | "DEBUG" | "ALL" - applies to both console and backend
  consoleEnabled: false, // Enable/disable console logging
  source: "reclaim-extension-sdk",
};

export const LOG_CONFIG_STORAGE_KEY = "reclaim_extension_sdk_log_config";
